// Replays every P2 recording through the live capture logic (web/noise.js) and
// writes lessons/GATE-REPORT.md: each segment's time, duration, SNR, and whether
// it reached ASR or became a gap, plus which human-labelled lines it covers.
//
//   node lessons/tools/gate-report.mjs [--hangover 0.35] [--snr 12]

import { readFileSync, writeFileSync } from 'node:fs';
import { Segmenter, DEFAULTS } from '../../web/noise.js';

const root = new URL('../', import.meta.url);
const arg = (name, fallback) => {
  const i = process.argv.indexOf(name);
  return i > 0 ? Number(process.argv[i + 1]) : fallback;
};
const opts = { hangoverSec: arg('--hangover', DEFAULTS.hangoverSec), snrThresholdDb: arg('--snr', DEFAULTS.snrThresholdDb) };

const RUNS = [
  ['sample/lesson-clean.wav', 'gold/lesson-clean.labels.txt'],
  ['sample/lesson-noisy.wav', 'gold/lesson-noisy.labels.txt'],
  ['sample/noise-only.wav', null],
  ['sweep/lesson-snr20.wav', 'gold/lesson-clean.labels.txt'],
  ['sweep/lesson-snr10.wav', 'gold/lesson-clean.labels.txt'],
  ['sweep/lesson-snr5.wav', 'gold/lesson-clean.labels.txt'],
  ['sweep/lesson-snr0.wav', 'gold/lesson-clean.labels.txt'],
];

export function readWav(url) {
  const b = readFileSync(url);
  for (let o = 12; o < b.length;) {
    const id = b.toString('ascii', o, o + 4);
    const size = b.readUInt32LE(o + 4);
    if (id === 'data') {
      const d = b.subarray(o + 8, o + 8 + size);
      const f = new Float32Array(d.length / 2);
      for (let i = 0; i < f.length; i++) f[i] = d.readInt16LE(i * 2) / 32768;
      return f;
    }
    o += 8 + size + (size & 1);
  }
  throw new Error(`no data chunk in ${url}`);
}

export function segmentFile(url, o = opts) {
  const s = new Segmenter(o);
  const out = [];
  s.onSegment((seg) => out.push(seg));
  const pcm = readWav(url);
  for (let i = 0; i < pcm.length; i += 2048) s.push(pcm.subarray(i, i + 2048));
  s.flush();
  return out;
}

export function readLabels(url) {
  return readFileSync(url, 'utf8').trim().split('\n').map((l, i) => {
    const [a, b, text] = l.split('\t');
    return { n: i + 1, start: Number(a), end: Number(b), text };
  });
}

const lines = [
  '# Gate report (P2)',
  '',
  `Generated by \`node lessons/tools/gate-report.mjs\` from the real recordings. Settings: SNR gate **${opts.snrThresholdDb} dB**, ` +
    `min duration **${DEFAULTS.minSpeechSec} s**, hangover **${opts.hangoverSec} s**, steady-noise std < ${DEFAULTS.steadyStdDb} dB.`,
  '"Lines" are the human-labelled lines whose midpoint falls inside a segment.',
  '',
];
const summary = ['| Recording | Segments | To ASR | Gaps | Labelled lines reaching ASR |', '| --- | ---: | ---: | ---: | --- |'];
const detail = [];

for (const [wav, lab] of RUNS) {
  const segs = segmentFile(new URL(wav, root));
  const labels = lab ? readLabels(new URL(lab, root)) : [];
  const covers = (s) => labels.filter((l) => s.startSec <= (l.start + l.end) / 2 && (l.start + l.end) / 2 <= s.endSec).map((l) => l.n);
  const passed = segs.filter((s) => !s.reason);
  const reached = labels.filter((l) => passed.some((s) => covers(s).includes(l.n)));
  const missed = labels.filter((l) => !reached.includes(l)).map((l) => l.n);
  summary.push(`| \`${wav}\` | ${segs.length} | ${passed.length} | ${segs.length - passed.length} | ` +
    (lab ? `${reached.length}/${labels.length}${missed.length ? ` (missing ${missed.join(', ')})` : ''}` : 'no speech — should be 0 to ASR') + ' |');
  detail.push('', `### \`${wav}\``, '', '| # | Start | End | Dur s | SNR dB | Result | Lines |', '| ---: | ---: | ---: | ---: | ---: | --- | --- |');
  segs.forEach((s, i) => detail.push(`| ${i + 1} | ${s.startSec.toFixed(2)} | ${s.endSec.toFixed(2)} | ${(s.endSec - s.startSec).toFixed(2)} | ` +
    `${s.snrDb.toFixed(1)} | ${s.reason ?? '**ASR**'} | ${covers(s).join(', ')} |`));
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  writeFileSync(new URL('GATE-REPORT.md', root), [...lines, '## Summary', '', ...summary, '', '## Every segment', ...detail, ''].join('\n'));
  console.log(summary.join('\n'));
}
